#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TAS2013_NHA")]
	public partial class ReportsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEmp(Emp instance);
    partial void UpdateEmp(Emp instance);
    partial void DeleteEmp(Emp instance);
    #endregion
		
		public ReportsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TAS2013_NHAConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ReportsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Emp> Emps
		{
			get
			{
				return this.GetTable<Emp>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Emp")]
	public partial class Emp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EmpID;
		
		private string _EmpNo;
		
		private string _EmpName;
		
		private System.Nullable<int> _DesigID;
		
		private System.Nullable<short> _JobID;
		
		private System.Nullable<byte> _Gender;
		
		private System.Nullable<byte> _ShiftID;
		
		private System.Nullable<short> _LocID;
		
		private System.Nullable<byte> _TypeID;
		
		private System.Nullable<byte> _GradeID;
		
		private System.Nullable<short> _SecID;
		
		private string _CardNo;
		
		private System.Nullable<int> _FpID;
		
		private string _PinCode;
		
		private string _NicNo;
		
		private string _FatherName;
		
		private string _BloodGroup;
		
		private System.Nullable<System.DateTime> _BirthDate;
		
		private string _MarStatus;
		
		private System.Nullable<System.DateTime> _JoinDate;
		
		private System.Nullable<System.DateTime> _ValidDate;
		
		private System.Nullable<System.DateTime> _IssueDate;
		
		private System.Nullable<System.DateTime> _ResignDate;
		
		private string _HomeAdd;
		
		private bool _ProcessAtt;
		
		private bool _ProcessIn;
		
		private System.Nullable<bool> _Status;
		
		private string _PhoneNo;
		
		private string _Remarks;
		
		private string _Email;
		
		private string _CellNo;
		
		private System.Nullable<short> _CrewID;
		
		private System.Nullable<bool> _FlagFP;
		
		private System.Nullable<bool> _FlagFace;
		
		private System.Nullable<bool> _FlagCard;
		
		private System.Nullable<int> _EmpImageID;
		
		private System.Nullable<short> _CompanyID;
		
		private System.Nullable<bool> _Presence;
		
		private System.Nullable<short> _ReaderID;
		
		private System.Nullable<System.DateTime> _LastEntryDateTime;
		
		private System.Nullable<bool> _IsSafe;
		
		private System.Nullable<bool> _HasOT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmpIDChanging(int value);
    partial void OnEmpIDChanged();
    partial void OnEmpNoChanging(string value);
    partial void OnEmpNoChanged();
    partial void OnEmpNameChanging(string value);
    partial void OnEmpNameChanged();
    partial void OnDesigIDChanging(System.Nullable<int> value);
    partial void OnDesigIDChanged();
    partial void OnJobIDChanging(System.Nullable<short> value);
    partial void OnJobIDChanged();
    partial void OnGenderChanging(System.Nullable<byte> value);
    partial void OnGenderChanged();
    partial void OnShiftIDChanging(System.Nullable<byte> value);
    partial void OnShiftIDChanged();
    partial void OnLocIDChanging(System.Nullable<short> value);
    partial void OnLocIDChanged();
    partial void OnTypeIDChanging(System.Nullable<byte> value);
    partial void OnTypeIDChanged();
    partial void OnGradeIDChanging(System.Nullable<byte> value);
    partial void OnGradeIDChanged();
    partial void OnSecIDChanging(System.Nullable<short> value);
    partial void OnSecIDChanged();
    partial void OnCardNoChanging(string value);
    partial void OnCardNoChanged();
    partial void OnFpIDChanging(System.Nullable<int> value);
    partial void OnFpIDChanged();
    partial void OnPinCodeChanging(string value);
    partial void OnPinCodeChanged();
    partial void OnNicNoChanging(string value);
    partial void OnNicNoChanged();
    partial void OnFatherNameChanging(string value);
    partial void OnFatherNameChanged();
    partial void OnBloodGroupChanging(string value);
    partial void OnBloodGroupChanged();
    partial void OnBirthDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthDateChanged();
    partial void OnMarStatusChanging(string value);
    partial void OnMarStatusChanged();
    partial void OnJoinDateChanging(System.Nullable<System.DateTime> value);
    partial void OnJoinDateChanged();
    partial void OnValidDateChanging(System.Nullable<System.DateTime> value);
    partial void OnValidDateChanged();
    partial void OnIssueDateChanging(System.Nullable<System.DateTime> value);
    partial void OnIssueDateChanged();
    partial void OnResignDateChanging(System.Nullable<System.DateTime> value);
    partial void OnResignDateChanged();
    partial void OnHomeAddChanging(string value);
    partial void OnHomeAddChanged();
    partial void OnProcessAttChanging(bool value);
    partial void OnProcessAttChanged();
    partial void OnProcessInChanging(bool value);
    partial void OnProcessInChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    partial void OnPhoneNoChanging(string value);
    partial void OnPhoneNoChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCellNoChanging(string value);
    partial void OnCellNoChanged();
    partial void OnCrewIDChanging(System.Nullable<short> value);
    partial void OnCrewIDChanged();
    partial void OnFlagFPChanging(System.Nullable<bool> value);
    partial void OnFlagFPChanged();
    partial void OnFlagFaceChanging(System.Nullable<bool> value);
    partial void OnFlagFaceChanged();
    partial void OnFlagCardChanging(System.Nullable<bool> value);
    partial void OnFlagCardChanged();
    partial void OnEmpImageIDChanging(System.Nullable<int> value);
    partial void OnEmpImageIDChanged();
    partial void OnCompanyIDChanging(System.Nullable<short> value);
    partial void OnCompanyIDChanged();
    partial void OnPresenceChanging(System.Nullable<bool> value);
    partial void OnPresenceChanged();
    partial void OnReaderIDChanging(System.Nullable<short> value);
    partial void OnReaderIDChanged();
    partial void OnLastEntryDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastEntryDateTimeChanged();
    partial void OnIsSafeChanging(System.Nullable<bool> value);
    partial void OnIsSafeChanged();
    partial void OnHasOTChanging(System.Nullable<bool> value);
    partial void OnHasOTChanged();
    #endregion
		
		public Emp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EmpID
		{
			get
			{
				return this._EmpID;
			}
			set
			{
				if ((this._EmpID != value))
				{
					this.OnEmpIDChanging(value);
					this.SendPropertyChanging();
					this._EmpID = value;
					this.SendPropertyChanged("EmpID");
					this.OnEmpIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EmpNo
		{
			get
			{
				return this._EmpNo;
			}
			set
			{
				if ((this._EmpNo != value))
				{
					this.OnEmpNoChanging(value);
					this.SendPropertyChanging();
					this._EmpNo = value;
					this.SendPropertyChanged("EmpNo");
					this.OnEmpNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EmpName
		{
			get
			{
				return this._EmpName;
			}
			set
			{
				if ((this._EmpName != value))
				{
					this.OnEmpNameChanging(value);
					this.SendPropertyChanging();
					this._EmpName = value;
					this.SendPropertyChanged("EmpName");
					this.OnEmpNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DesigID", DbType="Int")]
		public System.Nullable<int> DesigID
		{
			get
			{
				return this._DesigID;
			}
			set
			{
				if ((this._DesigID != value))
				{
					this.OnDesigIDChanging(value);
					this.SendPropertyChanging();
					this._DesigID = value;
					this.SendPropertyChanged("DesigID");
					this.OnDesigIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobID", DbType="SmallInt")]
		public System.Nullable<short> JobID
		{
			get
			{
				return this._JobID;
			}
			set
			{
				if ((this._JobID != value))
				{
					this.OnJobIDChanging(value);
					this.SendPropertyChanging();
					this._JobID = value;
					this.SendPropertyChanged("JobID");
					this.OnJobIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="TinyInt")]
		public System.Nullable<byte> Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShiftID", DbType="TinyInt")]
		public System.Nullable<byte> ShiftID
		{
			get
			{
				return this._ShiftID;
			}
			set
			{
				if ((this._ShiftID != value))
				{
					this.OnShiftIDChanging(value);
					this.SendPropertyChanging();
					this._ShiftID = value;
					this.SendPropertyChanged("ShiftID");
					this.OnShiftIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocID", DbType="SmallInt")]
		public System.Nullable<short> LocID
		{
			get
			{
				return this._LocID;
			}
			set
			{
				if ((this._LocID != value))
				{
					this.OnLocIDChanging(value);
					this.SendPropertyChanging();
					this._LocID = value;
					this.SendPropertyChanged("LocID");
					this.OnLocIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeID", DbType="TinyInt")]
		public System.Nullable<byte> TypeID
		{
			get
			{
				return this._TypeID;
			}
			set
			{
				if ((this._TypeID != value))
				{
					this.OnTypeIDChanging(value);
					this.SendPropertyChanging();
					this._TypeID = value;
					this.SendPropertyChanged("TypeID");
					this.OnTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeID", DbType="TinyInt")]
		public System.Nullable<byte> GradeID
		{
			get
			{
				return this._GradeID;
			}
			set
			{
				if ((this._GradeID != value))
				{
					this.OnGradeIDChanging(value);
					this.SendPropertyChanging();
					this._GradeID = value;
					this.SendPropertyChanged("GradeID");
					this.OnGradeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecID", DbType="SmallInt")]
		public System.Nullable<short> SecID
		{
			get
			{
				return this._SecID;
			}
			set
			{
				if ((this._SecID != value))
				{
					this.OnSecIDChanging(value);
					this.SendPropertyChanging();
					this._SecID = value;
					this.SendPropertyChanged("SecID");
					this.OnSecIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardNo", DbType="Char(10)")]
		public string CardNo
		{
			get
			{
				return this._CardNo;
			}
			set
			{
				if ((this._CardNo != value))
				{
					this.OnCardNoChanging(value);
					this.SendPropertyChanging();
					this._CardNo = value;
					this.SendPropertyChanged("CardNo");
					this.OnCardNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FpID", DbType="Int")]
		public System.Nullable<int> FpID
		{
			get
			{
				return this._FpID;
			}
			set
			{
				if ((this._FpID != value))
				{
					this.OnFpIDChanging(value);
					this.SendPropertyChanging();
					this._FpID = value;
					this.SendPropertyChanged("FpID");
					this.OnFpIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PinCode", DbType="Char(4)")]
		public string PinCode
		{
			get
			{
				return this._PinCode;
			}
			set
			{
				if ((this._PinCode != value))
				{
					this.OnPinCodeChanging(value);
					this.SendPropertyChanging();
					this._PinCode = value;
					this.SendPropertyChanged("PinCode");
					this.OnPinCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NicNo", DbType="NVarChar(50)")]
		public string NicNo
		{
			get
			{
				return this._NicNo;
			}
			set
			{
				if ((this._NicNo != value))
				{
					this.OnNicNoChanging(value);
					this.SendPropertyChanging();
					this._NicNo = value;
					this.SendPropertyChanged("NicNo");
					this.OnNicNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatherName", DbType="NVarChar(50)")]
		public string FatherName
		{
			get
			{
				return this._FatherName;
			}
			set
			{
				if ((this._FatherName != value))
				{
					this.OnFatherNameChanging(value);
					this.SendPropertyChanging();
					this._FatherName = value;
					this.SendPropertyChanged("FatherName");
					this.OnFatherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloodGroup", DbType="NVarChar(6)")]
		public string BloodGroup
		{
			get
			{
				return this._BloodGroup;
			}
			set
			{
				if ((this._BloodGroup != value))
				{
					this.OnBloodGroupChanging(value);
					this.SendPropertyChanging();
					this._BloodGroup = value;
					this.SendPropertyChanged("BloodGroup");
					this.OnBloodGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthDate", DbType="Date")]
		public System.Nullable<System.DateTime> BirthDate
		{
			get
			{
				return this._BirthDate;
			}
			set
			{
				if ((this._BirthDate != value))
				{
					this.OnBirthDateChanging(value);
					this.SendPropertyChanging();
					this._BirthDate = value;
					this.SendPropertyChanged("BirthDate");
					this.OnBirthDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarStatus", DbType="NVarChar(15)")]
		public string MarStatus
		{
			get
			{
				return this._MarStatus;
			}
			set
			{
				if ((this._MarStatus != value))
				{
					this.OnMarStatusChanging(value);
					this.SendPropertyChanging();
					this._MarStatus = value;
					this.SendPropertyChanged("MarStatus");
					this.OnMarStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JoinDate", DbType="Date")]
		public System.Nullable<System.DateTime> JoinDate
		{
			get
			{
				return this._JoinDate;
			}
			set
			{
				if ((this._JoinDate != value))
				{
					this.OnJoinDateChanging(value);
					this.SendPropertyChanging();
					this._JoinDate = value;
					this.SendPropertyChanged("JoinDate");
					this.OnJoinDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValidDate", DbType="Date")]
		public System.Nullable<System.DateTime> ValidDate
		{
			get
			{
				return this._ValidDate;
			}
			set
			{
				if ((this._ValidDate != value))
				{
					this.OnValidDateChanging(value);
					this.SendPropertyChanging();
					this._ValidDate = value;
					this.SendPropertyChanged("ValidDate");
					this.OnValidDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueDate", DbType="Date")]
		public System.Nullable<System.DateTime> IssueDate
		{
			get
			{
				return this._IssueDate;
			}
			set
			{
				if ((this._IssueDate != value))
				{
					this.OnIssueDateChanging(value);
					this.SendPropertyChanging();
					this._IssueDate = value;
					this.SendPropertyChanged("IssueDate");
					this.OnIssueDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResignDate", DbType="Date")]
		public System.Nullable<System.DateTime> ResignDate
		{
			get
			{
				return this._ResignDate;
			}
			set
			{
				if ((this._ResignDate != value))
				{
					this.OnResignDateChanging(value);
					this.SendPropertyChanging();
					this._ResignDate = value;
					this.SendPropertyChanged("ResignDate");
					this.OnResignDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeAdd", DbType="NVarChar(300)")]
		public string HomeAdd
		{
			get
			{
				return this._HomeAdd;
			}
			set
			{
				if ((this._HomeAdd != value))
				{
					this.OnHomeAddChanging(value);
					this.SendPropertyChanging();
					this._HomeAdd = value;
					this.SendPropertyChanged("HomeAdd");
					this.OnHomeAddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessAtt", DbType="Bit NOT NULL")]
		public bool ProcessAtt
		{
			get
			{
				return this._ProcessAtt;
			}
			set
			{
				if ((this._ProcessAtt != value))
				{
					this.OnProcessAttChanging(value);
					this.SendPropertyChanging();
					this._ProcessAtt = value;
					this.SendPropertyChanged("ProcessAtt");
					this.OnProcessAttChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessIn", DbType="Bit NOT NULL")]
		public bool ProcessIn
		{
			get
			{
				return this._ProcessIn;
			}
			set
			{
				if ((this._ProcessIn != value))
				{
					this.OnProcessInChanging(value);
					this.SendPropertyChanging();
					this._ProcessIn = value;
					this.SendPropertyChanged("ProcessIn");
					this.OnProcessInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNo", DbType="NVarChar(50)")]
		public string PhoneNo
		{
			get
			{
				return this._PhoneNo;
			}
			set
			{
				if ((this._PhoneNo != value))
				{
					this.OnPhoneNoChanging(value);
					this.SendPropertyChanging();
					this._PhoneNo = value;
					this.SendPropertyChanged("PhoneNo");
					this.OnPhoneNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(500)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellNo", DbType="NVarChar(50)")]
		public string CellNo
		{
			get
			{
				return this._CellNo;
			}
			set
			{
				if ((this._CellNo != value))
				{
					this.OnCellNoChanging(value);
					this.SendPropertyChanging();
					this._CellNo = value;
					this.SendPropertyChanged("CellNo");
					this.OnCellNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CrewID", DbType="SmallInt")]
		public System.Nullable<short> CrewID
		{
			get
			{
				return this._CrewID;
			}
			set
			{
				if ((this._CrewID != value))
				{
					this.OnCrewIDChanging(value);
					this.SendPropertyChanging();
					this._CrewID = value;
					this.SendPropertyChanged("CrewID");
					this.OnCrewIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagFP", DbType="Bit")]
		public System.Nullable<bool> FlagFP
		{
			get
			{
				return this._FlagFP;
			}
			set
			{
				if ((this._FlagFP != value))
				{
					this.OnFlagFPChanging(value);
					this.SendPropertyChanging();
					this._FlagFP = value;
					this.SendPropertyChanged("FlagFP");
					this.OnFlagFPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagFace", DbType="Bit")]
		public System.Nullable<bool> FlagFace
		{
			get
			{
				return this._FlagFace;
			}
			set
			{
				if ((this._FlagFace != value))
				{
					this.OnFlagFaceChanging(value);
					this.SendPropertyChanging();
					this._FlagFace = value;
					this.SendPropertyChanged("FlagFace");
					this.OnFlagFaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagCard", DbType="Bit")]
		public System.Nullable<bool> FlagCard
		{
			get
			{
				return this._FlagCard;
			}
			set
			{
				if ((this._FlagCard != value))
				{
					this.OnFlagCardChanging(value);
					this.SendPropertyChanging();
					this._FlagCard = value;
					this.SendPropertyChanged("FlagCard");
					this.OnFlagCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpImageID", DbType="Int")]
		public System.Nullable<int> EmpImageID
		{
			get
			{
				return this._EmpImageID;
			}
			set
			{
				if ((this._EmpImageID != value))
				{
					this.OnEmpImageIDChanging(value);
					this.SendPropertyChanging();
					this._EmpImageID = value;
					this.SendPropertyChanged("EmpImageID");
					this.OnEmpImageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="SmallInt")]
		public System.Nullable<short> CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this.OnCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyID = value;
					this.SendPropertyChanged("CompanyID");
					this.OnCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Presence", DbType="Bit")]
		public System.Nullable<bool> Presence
		{
			get
			{
				return this._Presence;
			}
			set
			{
				if ((this._Presence != value))
				{
					this.OnPresenceChanging(value);
					this.SendPropertyChanging();
					this._Presence = value;
					this.SendPropertyChanged("Presence");
					this.OnPresenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReaderID", DbType="SmallInt")]
		public System.Nullable<short> ReaderID
		{
			get
			{
				return this._ReaderID;
			}
			set
			{
				if ((this._ReaderID != value))
				{
					this.OnReaderIDChanging(value);
					this.SendPropertyChanging();
					this._ReaderID = value;
					this.SendPropertyChanged("ReaderID");
					this.OnReaderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastEntryDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastEntryDateTime
		{
			get
			{
				return this._LastEntryDateTime;
			}
			set
			{
				if ((this._LastEntryDateTime != value))
				{
					this.OnLastEntryDateTimeChanging(value);
					this.SendPropertyChanging();
					this._LastEntryDateTime = value;
					this.SendPropertyChanged("LastEntryDateTime");
					this.OnLastEntryDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSafe", DbType="Bit")]
		public System.Nullable<bool> IsSafe
		{
			get
			{
				return this._IsSafe;
			}
			set
			{
				if ((this._IsSafe != value))
				{
					this.OnIsSafeChanging(value);
					this.SendPropertyChanging();
					this._IsSafe = value;
					this.SendPropertyChanged("IsSafe");
					this.OnIsSafeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasOT", DbType="Bit")]
		public System.Nullable<bool> HasOT
		{
			get
			{
				return this._HasOT;
			}
			set
			{
				if ((this._HasOT != value))
				{
					this.OnHasOTChanging(value);
					this.SendPropertyChanging();
					this._HasOT = value;
					this.SendPropertyChanged("HasOT");
					this.OnHasOTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
