//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpPosting
    {
        public int PostingID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> PostingDesignation { get; set; }
        public Nullable<int> ActualDesignation { get; set; }
        public Nullable<byte> PostingBS { get; set; }
        public Nullable<byte> ActualBS { get; set; }
        public Nullable<short> Status { get; set; }
        public string PresentPostingRemarks { get; set; }
        public Nullable<short> DomiID { get; set; }
        public Nullable<short> CadreID { get; set; }
        public Nullable<bool> OwnPayscale { get; set; }
        public string PayScaleRemarks { get; set; }
        public Nullable<bool> AdditionalCharge { get; set; }
        public string AdditionalChargeRemarks { get; set; }
        public Nullable<bool> LookAfterCharge { get; set; }
        public string LookAfterChargeRemarks { get; set; }
        public Nullable<short> PostingFromLoc { get; set; }
        public Nullable<short> PostingToLoc { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<bool> AwaitingForPosting { get; set; }
        public string Remarks { get; set; }
        public Nullable<short> OldWingID { get; set; }
        public Nullable<short> OldSectionID { get; set; }
        public Nullable<short> NewWingID { get; set; }
        public Nullable<short> NewSectionID { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual Cadre Cadre { get; set; }
        public virtual Domicile Domicile { get; set; }
        public virtual Emp Emp { get; set; }
        public virtual Project Project { get; set; }
    }
}
