//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermission
    {
        public int UserPerID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CriteriaType { get; set; }
        public Nullable<short> CriteriaValue { get; set; }
    
        public virtual User User { get; set; }
    }
}
