//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewServiceLog
    {
        public Nullable<bool> Processed { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Description { get; set; }
        public byte ErrorCode { get; set; }
        public int LogID { get; set; }
        public string RdrName { get; set; }
        public string IpAdd { get; set; }
    }
}
