//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone
    {
        public short ZoneID { get; set; }
        public string ZoneName { get; set; }
<<<<<<< HEAD
        public Nullable<short> RegionID { get; set; }
=======
>>>>>>> f2386b6df7c17d9c6a97b4400f2810bc70fb9fc2
    }
}
